pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - status-success=Sider
      - status-success=Semantic Pull Request
      - status-success=Python MariaDB
      - status-success=Python PostgreSQL
      - status-success=UI MariaDB
      - status-success=security/snyk (frappe)
      - label!=dont-merge
      - label!=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic squash on CI success and review
    conditions:
      - status-success=Sider
      - status-success=Python MariaDB
      - status-success=Python PostgreSQL
      - status-success=UI MariaDB
      - status-success=security/snyk (frappe)
      - label!=dont-merge
      - label=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
